CREATE TABLE STUDENT
(
    STUDENT_ID NUMBER(5) PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30),
    COURSE VARCHAR2(20),
    MARKS NUMBER(3)
);

SET SERVEROUTPUT ON;

BEGIN
    INSERT INTO STUDENT
    VALUES (101, 'Ravi', 'CSE', 85);

    SAVEPOINT SP1;

    INSERT INTO STUDENT
    VALUES (102, 'Sita', 'CSE', 92);

    INSERT INTO STUDENT
    VALUES (103, 'Kiran', 'ECE', 78);

    ROLLBACK TO SP1;

    INSERT INTO STUDENT
    VALUES (104, 'Anjali', 'EEE', 88);

    COMMIT;

    DBMS_OUTPUT.PUT_LINE(
        'INSERT, SAVEPOINT, ROLLBACK and COMMIT completed successfully.'
    );

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

SELECT * FROM STUDENT;