SET SERVEROUTPUT ON;

-- 1. DROP OLD TABLE IF IT EXISTS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STUDENT12';
EXCEPTION
    WHEN OTHERS THEN
        NULL;
END;
/

-- 2. CREATE TABLE

CREATE TABLE STUDENT12
(
    STUDENT_ID NUMBER(4) PRIMARY KEY,
    STUDENT_NAME VARCHAR2(30),
    COURSE VARCHAR2(20),
    MARKS NUMBER(3)
);

-- 3. INSERT DATA

INSERT INTO STUDENT12 VALUES (101, 'Rahul', 'B.Tech', 82);
INSERT INTO STUDENT12 VALUES (102, 'Sneha', 'B.Tech', 74);
INSERT INTO STUDENT12 VALUES (103, 'Arjun', 'BCA', 58);
INSERT INTO STUDENT12 VALUES (104, 'Priya', 'B.Sc', 91);
INSERT INTO STUDENT12 VALUES (105, 'Kiran', 'BCA', 45);

COMMIT;

-- 4. CREATE FUNCTION

CREATE OR REPLACE FUNCTION COUNT_STUDENTS
(
    P_COURSE IN VARCHAR2
)
RETURN NUMBER
IS
    V_TOTAL NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO V_TOTAL
    FROM STUDENT12
    WHERE COURSE = P_COURSE;

    RETURN V_TOTAL;
END;
/

-- 5. CALL FUNCTION USING PL/SQL BLOCK

DECLARE
    V_BTECH NUMBER;
    V_BCA NUMBER;
    V_BSC NUMBER;
BEGIN

    V_BTECH := COUNT_STUDENTS('B.Tech');
    V_BCA := COUNT_STUDENTS('BCA');
    V_BSC := COUNT_STUDENTS('B.Sc');

    DBMS_OUTPUT.PUT_LINE('B.Tech Students : ' || V_BTECH);
    DBMS_OUTPUT.PUT_LINE('BCA Students    : ' || V_BCA);
    DBMS_OUTPUT.PUT_LINE('B.Sc Students   : ' || V_BSC);

END;
/