SELECT * FROM ACCOUNT;
SET SERVEROUTPUT ON;

-- Create ACCOUNT table

CREATE TABLE ACCOUNT
(
    ACCOUNT_NO NUMBER(6) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(30),
    ACCOUNT_TYPE VARCHAR2(20),
    BALANCE NUMBER(10,2)
);

-- Insert sample records

INSERT INTO ACCOUNT VALUES (100001, 'Rahul', 'SAVINGS', 25000);
INSERT INTO ACCOUNT VALUES (100002, 'Sneha', 'CURRENT', 45000);
INSERT INTO ACCOUNT VALUES (100003, 'Arjun', 'SAVINGS', 30000);
INSERT INTO ACCOUNT VALUES (100004, 'Priya', 'CURRENT', 55000);
INSERT INTO ACCOUNT VALUES (100005, 'Kiran', 'SAVINGS', 20000);

COMMIT;

-- Parameterized Cursor

DECLARE

    CURSOR C_ACCOUNT(P_ACCOUNT_TYPE VARCHAR2) IS
        SELECT ACCOUNT_NO,
               CUSTOMER_NAME,
               ACCOUNT_TYPE,
               BALANCE
        FROM ACCOUNT
        WHERE ACCOUNT_TYPE = P_ACCOUNT_TYPE;

BEGIN

    DBMS_OUTPUT.PUT_LINE('Accounts with SAVINGS Type');
    DBMS_OUTPUT.PUT_LINE('----------------------------');

    FOR REC IN C_ACCOUNT('SAVINGS') LOOP

        DBMS_OUTPUT.PUT_LINE(
            'Account No: ' || REC.ACCOUNT_NO ||
            '  Customer Name: ' || REC.CUSTOMER_NAME ||
            '  Account Type: ' || REC.ACCOUNT_TYPE ||
            '  Balance: ' || REC.BALANCE
        );

    END LOOP;

END;
/