SELECT * FROM EMPLOYEE;

--Q1
CREATE VIEW EMP_VIEW AS
SELECT * FROM EMPLOYEE;
CREATE TABLE DEPT
(
    DNO NUMBER PRIMARY KEY,
    DNAME VARCHAR2(30) NOT NULL
);

--Q2
CREATE TABLE STUDENT1
(
    SID NUMBER PRIMARY KEY,
    SNAME VARCHAR2(30) NOT NULL,
    DID NUMBER
);
    
--Q3
ALTER TABLE STUDENT1
ADD CONSTRAINT FK_DID
FOREIGN KEY(DID)
REFERENCES DEPT(DNO);

--Q4
ALTER TABLE STUDENT1
ADD CONSTRAINT_STUDENT PRIMARY KEY(SID),
ALTER TABLE STUDENT1
MODIFY SNAME,NOTNULL?
ALTER TABLE STUDENT1
ADD CONSTRAINT FK_STUDENT_DEPT
FOREIGN KEY(DID)
REFERENCES DEPT(DNO);

--Q5
INSERT INTO DEPT VALUES (10, 'CSE');
INSERT INTO DEPT VALUES (20, 'ME');
INSERT INTO DEPT VALUES (30, 'CE');
INSERT INTO DEPT VALUES (40, 'EEE');
INSERT INTO DEPT VALUES (50, 'ECE');
INSERT INTO DEPT VALUES (60, 'CSM');
INSERT INTO DEPT VALUES (70, 'CSD');

COMMIT;

--Q6
INSERT INTO STUDENT1 VALUES (101, 'Rahul', 10);
INSERT INTO STUDENT1 VALUES (102, 'Sneha', 20);
INSERT INTO STUDENT1 VALUES (103, 'Arjun', 10);
INSERT INTO STUDENT1 VALUES (104, 'Priya', 30);
INSERT INTO STUDENT1 VALUES (105, 'Kiran', 40);
INSERT INTO STUDENT1 VALUES (106, 'Nikhil', 50);
INSERT INTO STUDENT1 VALUES (107, 'Anjali', 60);
INSERT INTO STUDENT1 VALUES (108, 'Ravi', 10);
INSERT INTO STUDENT1 VALUES (109, 'Pooja', 20);
INSERT INTO STUDENT1 VALUES (110, 'Aman', NULL);

COMMIT;

--Q7
SELECT SID, SNAME, DNO, DNAME
FROM STUDENT1 S
JOIN DEPT D
ON S.DID=D.DNO;


--Q8
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
INNER JOIN DEPT D
ON S.DID = D.DNO;

--Q9
SELECT S.SID,
       S.SNAME,
       D.DNO,
       D.DNAME
FROM STUDENT1 S
JOIN DEPT D
ON S.DID > D.DNO;

--Q10
SELECT S.SID,S.SNAME,S.DID,D.DNAME
FROM STUDENT1 S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q11
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q12
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q13
SELECT S.SID,S.SNAME,D.DNAME
FROM STUDENT1 S
LEFT OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q14
SELECT S.SID,S.SNAME,D.DNAME
FROM STUDENT1 S
RIGHT OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q15
SELECT S.SID,S.SNAME,D.DNAME
FROM STUDENT1 S
FULL OUTER JOIN DEPT D
ON S.DID = D.DNO;

--Q16
DESC EMP_BASIC;
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
LEFT OUTER JOIN DEPT D
ON S.DID >= D.DNO;

--Q17
SELECT *
FROM IT_EMPLOYEES;
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
RIGHT OUTER JOIN DEPT D
ON S.DID >= D.DNO;

--Q18
SELECT * FROM HIGH_SALARY
WHERE SALARY > 70000;
SELECT S.SID,S.SNAME,D.DNO,D.DNAME
FROM STUDENT1 S
FULL OUTER JOIN DEPT D
ON S.DID >= D.DNO;

--Q19
SELECT S.SID,S.SNAME,D.DNO,D.DNAME FROM STUDENT1 S
CROSS JOIN DEPT D;