SET SERVEROUTPUT ON;

-- CREATE PROCEDURE WITH IN AND OUT PARAMETERS

CREATE OR REPLACE PROCEDURE GET_STUDENT_DETAILS
(
    P_ID IN NUMBER,
    P_NAME OUT VARCHAR2,
    P_MARKS OUT NUMBER
)
IS
BEGIN
    SELECT STUDENT_NAME, MARKS
    INTO P_NAME, P_MARKS
    FROM STUDENT
    WHERE STUDENT_ID = P_ID;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        P_NAME := 'Student Not Found';
        P_MARKS := NULL;
END;
/

-- CALL PROCEDURE

DECLARE
    V_NAME VARCHAR2(30);
    V_MARKS NUMBER(3);

BEGIN
    GET_STUDENT_DETAILS(101, V_NAME, V_MARKS);

    DBMS_OUTPUT.PUT_LINE('Student ID   : 101');
    DBMS_OUTPUT.PUT_LINE('Student Name : ' || V_NAME);
    DBMS_OUTPUT.PUT_LINE('Marks        : ' || V_MARKS);
END;
/