SET SERVEROUTPUT ON;

-- CREATE EMPLOYEE TABLE
CREATE TABLE EMPLOYEE_NEW
(
    EMPLOYEE_ID NUMBER(5) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(30),
    MONTHLY_SALARY NUMBER(10,2)
);

-- INSERT DATA
INSERT INTO EMPLOYEE_NEW VALUES (101, 'Ravi', 25000);
INSERT INTO EMPLOYEE_NEW VALUES (102, 'Sita', 30000);
INSERT INTO EMPLOYEE_NEW VALUES (103, 'Kiran', 35000);
INSERT INTO EMPLOYEE_NEW VALUES (104, 'Anjali', 40000);
INSERT INTO EMPLOYEE_NEW VALUES (105, 'Rahul', 45000);

COMMIT;

-- CREATE FUNCTION
CREATE OR REPLACE FUNCTION CALCULATE_ANNUAL_SALARY
(
    P_MONTHLY_SALARY IN NUMBER
)
RETURN NUMBER
IS
BEGIN
    RETURN P_MONTHLY_SALARY * 12;
END;
/

-- CALL FUNCTION
SELECT
    EMPLOYEE_ID,
    EMPLOYEE_NAME,
    MONTHLY_SALARY,
    CALCULATE_ANNUAL_SALARY(MONTHLY_SALARY) AS ANNUAL_SALARY
FROM EMPLOYEE_NEW;