SET SERVEROUTPUT ON;


-- Create EMPLOYEE table
CREATE TABLE EMPLOYEE18
(
    EMPLOYEE_ID NUMBER(4) PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR2(30),
    DEPARTMENT VARCHAR2(20),
    SALARY NUMBER(10,2)
);

-- Create DELETE LOG table
CREATE TABLE DELETE_LOG
(
    LOG_ID NUMBER(4),
    MESSAGE VARCHAR2(100)
);

-- Insert sample employee records
INSERT INTO EMPLOYEE18 VALUES (101, 'Rahul', 'HR', 35000);
INSERT INTO EMPLOYEE18 VALUES (102, 'Sneha', 'Sales', 42000);
INSERT INTO EMPLOYEE18 VALUES (103, 'Arjun', 'Finance', 45000);
INSERT INTO EMPLOYEE18 VALUES (104, 'Priya', 'IT', 40000);

COMMIT;

-- Create AFTER DELETE Statement-Level Trigger
CREATE OR REPLACE TRIGGER TRG_AFTER_DELETE
AFTER DELETE
ON EMPLOYEE18
BEGIN
    INSERT INTO DELETE_LOG
    VALUES (1, 'DELETE operation completed successfully.');

    DBMS_OUTPUT.PUT_LINE(
        'DELETE operation completed successfully.'
    );
END;
/

-- Delete multiple employee records
DELETE FROM EMPLOYEE18
WHERE EMPLOYEE_ID IN (101, 102);

COMMIT;

-- Display remaining EMPLOYEE records
SELECT *
FROM EMPLOYEE18;

-- Display DELETE LOG
SELECT *
FROM DELETE_LOG;